/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ProductosController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.ModelProductos;

/**
 *
 * @author Allan
 */
public class AddArticulo extends javax.swing.JDialog {

    /**
     * Creates new form AddArticulo
     */
    Principal prin;
    
    public AddArticulo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        init();
        prin = (Principal) parent;
     
    }
    
    public AddArticulo(java.awt.Frame parent, boolean modal,ProductosController connect) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        init();
        prin = (Principal) parent;
        this.connect = connect;
    }
    public int contador;
    private ArrayList<String> arrayPreguntas ;
    
    public void init() {
        
        contador = 0;
        
        arrayPreguntas = new ArrayList<>();
        arrayPreguntas.add("ID Articulo:");
        arrayPreguntas.add("Nombre Articulo:");
        arrayPreguntas.add("Descripción del Articulo:");
        arrayPreguntas.add("Cantidad Actual:");
        arrayPreguntas.add("Cantidad Mínima Permitida");
        arrayPreguntas.add("Cantidad Máxima Permitida");
        arrayPreguntas.add("Unidad Medida");
        arrayPreguntas.add("Contraseña Usuario");
        
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 168, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Siguiente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("       ID Articulo:");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("<Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Añadir un Articulo al Inventario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(10, 10, 10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(97, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
   
    setPregunta(jTextField1.getText());
  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
    contador = contador - 1;
    setPregunta("Atras");
    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddArticulo dialog = new AddArticulo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
     
    ModelProductos producto = new ModelProductos();;
     
    private void setPregunta(String x) {
        
        
         if (contador == 9) {
            this.dispose();
            prin.initAll();
        }else{
         
        if ((x.isEmpty()) | (x.equals(" "))) {
            jLabel3.setText("No dejes este espacio vacío");

        }
        else{
        if ((contador < 0)) {
            contador = 0;
        }
        
       
        if (contador == 7) {
            
            CheckPass(x);

        }

        
        if (x.equals("Atras")) {
            
            DoBack();
           
            jLabel4.setText(contador + "");
            jLabel3.setText("");
        } else {

            if(DoNext(x)){
            jLabel3.setText("Set To: " + x);
            jTextField1.setText("");
            contador = contador + 1;
            jLabel4.setText(contador + "");}
            

        }
        if (contador < 7) {
            jLabel2.setText(arrayPreguntas.get(contador));
         }
        }
       }
    }
    
    public void DoBack(){
        switch (contador) {

                case 0:
                    jTextField1.setText(producto.getIdProducto());
                    break;
                case 1:
                     jTextField1.setText(producto.getNombre());
                    break;
                case 2:
                     jTextField1.setText(producto.getDescripcion());
                    break;
                case 3:
                    jTextField1.setText(producto.getCantidad());
                    break;
                case 4:
                     jTextField1.setText(producto.getCantidad_minima());
                    break;
                case 5:
                    jTextField1.setText(producto.getCantidad_maxima());
                    break;
                case 6:
                     jTextField1.setText(producto.getUnidad_medida());
                     
                    break;
            
            }
    }
    
    public boolean DoNext(String x){
        boolean ret = true;
        switch (contador) {

            case 0:
                boolean checkID = checkID(x);
                if (checkID) {
                    producto.setIdProducto(x);
                } else {
                    ret = false;
                    JOptionPane.showMessageDialog(this, "No puedo insertar, ya hay un articulo con ese ID");
                }
                break;
            case 1:
                producto.setNombre(x);
                break;
            case 2:
                producto.setDescripcion(x);
                break;
            case 3:
                producto.setCantidad(x);
                break;
            case 4:
                producto.setCantidad_minima(x);
                break;
            case 5:
                producto.setCantidad_maxima(x);
                break;
            case 6:
                producto.setUnidad_medida(x);
                jLabel2.setText("Digite PassWord de Usuario");
                break;

            }
        return ret;
    }

    public void CheckPass(String x){
         if ((x.equals("1234")|(x.equals("4321")))) {
                
                producto.setUsuario_actualiza(x);
                producto.setUsuario_registra(x);
                
                boolean insertArticulo = prin.insertArticulo(producto);
                if(insertArticulo){
                jLabel2.setText("Producto Insertado Correctamente");
                jTextField1.setVisible(false);
                jLabel3.setVisible(false);
                jButton1.setVisible(false);
                contador = contador +1;
               
                }
            }else{
                jLabel2.setText("Valla Clave Incorrecta");
                contador = contador-1;
            }
    }
    
    ProductosController connect;
    
    private boolean checkID(String x) {
        boolean ret = true;
        ArrayList<ModelProductos> allProducts = connect.getAllProducts();
         int c = 0;
         while(c!=allProducts.size() ){
             ModelProductos model = allProducts.get(c);
             if(model.getIdProducto().equals(x)){
                 ret =  false;
             }
            c++;
         }
     return ret;
    }


}
